let frutas=[];
frutas[0]="Limon";
frutas[1]="Naranja";
frutas[2]="Sandia";
frutas[3]="Melon";
frutas[4]="Kiwi";
let ultima=frutas.pop();
console.log("La ultima fruta agregada fue: %s",ultima);
let primera=frutas.reverse();
console.log("La primer fruta agregada fue:%s ",primera.pop());